FROM python:3.13-bookworm

WORKDIR /app

# Копируем зависимости
COPY pyproject.toml .

# Установка uv и зависимостей
RUN pip install uv && uv pip install . --system --group tests

# Копируем остальные файлы
COPY . .

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]