FROM python:3.13-bookworm

WORKDIR /app

# Копируем зависимости
COPY pyproject.toml uv.lock ./

# Установка uv с dev-зависимостями
RUN pip install uv && \
    uv pip install -e ".[dev]"

# Копируем исходный код
COPY . .

CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]